from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
from reportlab.lib.enums import TA_LEFT

output = "/Users/nathanshiba/.openclaw/workspace/2heads-site/Shiba-Associates-Google-Ads-API-Design-Doc.pdf"

doc = SimpleDocTemplate(
    output,
    pagesize=letter,
    rightMargin=1*inch,
    leftMargin=1*inch,
    topMargin=1*inch,
    bottomMargin=1*inch
)

styles = getSampleStyleSheet()

title_style = ParagraphStyle(
    'Title',
    parent=styles['Heading1'],
    fontSize=16,
    spaceAfter=6,
    textColor=colors.HexColor('#1a1a1a'),
)

section_style = ParagraphStyle(
    'Section',
    parent=styles['Heading2'],
    fontSize=12,
    spaceBefore=14,
    spaceAfter=4,
    textColor=colors.HexColor('#2c5282'),
)

body_style = ParagraphStyle(
    'Body',
    parent=styles['Normal'],
    fontSize=10.5,
    leading=16,
    spaceAfter=8,
    textColor=colors.HexColor('#1a1a1a'),
)

bullet_style = ParagraphStyle(
    'Bullet',
    parent=body_style,
    leftIndent=20,
    bulletIndent=8,
    spaceAfter=4,
)

story = []

story.append(Paragraph("Google Ads API Tool — Design Document", title_style))
story.append(Paragraph("Shiba &amp; Associates", styles['Heading2']))
story.append(Spacer(1, 0.1*inch))
story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#cbd5e0')))
story.append(Spacer(1, 0.15*inch))

story.append(Paragraph("Company Name", section_style))
story.append(Paragraph("Shiba &amp; Associates", body_style))

story.append(Paragraph("Company Website", section_style))
story.append(Paragraph("https://2.0heads.com", body_style))

story.append(Paragraph("Business Model", section_style))
story.append(Paragraph(
    "Shiba &amp; Associates is a digital marketing consultancy that manages Google Ads programs "
    "for a portfolio of small and mid-sized business clients across multiple industries, including "
    "e-commerce, manufacturing, professional services, and food &amp; beverage. The company "
    "operates as a single-operator agency; all API access and tooling is managed internally by "
    "David Shiba.",
    body_style
))

story.append(Paragraph("Tool Access and Use", section_style))
story.append(Paragraph(
    "The tool is an internal reporting and account management system used exclusively by "
    "David Shiba (owner, Shiba &amp; Associates). No external users, clients, or third parties "
    "will have direct access to the tool or its interface. Clients receive report outputs "
    "(Excel/PDF files) generated by the tool, but cannot access the system itself.",
    body_style
))

story.append(Paragraph("Tool Design", section_style))
story.append(Paragraph(
    "The tool consists of Python scripts that authenticate to the Google Ads API using OAuth 2.0 "
    "and a developer token. The scripts perform the following functions:",
    body_style
))

story.append(Paragraph("• <b>Performance Reporting:</b> Pull campaign, ad group, keyword, and search term performance data for each client's Google Ads account. Data is retrieved for configurable date ranges (monthly, quarterly, custom) and written to structured Excel workbooks with pivot-ready formatting.", bullet_style))
story.append(Paragraph("• <b>Multi-Account Management:</b> Authenticate against a manager account (MCC) to access multiple client sub-accounts from a single token. Scripts iterate over authorized accounts to batch-pull data.", bullet_style))
story.append(Paragraph("• <b>Automated Monthly Reports:</b> Scripts are run manually at the end of each month to generate standardized performance reports per client. Reports include campaign spend, impressions, clicks, conversions, CTR, CPC, and ROAS.", bullet_style))
story.append(Paragraph("• <b>Budget Monitoring:</b> Query current campaign budgets and spend pacing to flag overpacing or underpacing accounts for manual review.", bullet_style))
story.append(Spacer(1, 0.05*inch))
story.append(Paragraph(
    "All data is stored locally on the operator's machine. There is no shared database, "
    "no web application layer, and no public-facing interface. The tool is a command-line "
    "Python script suite run on demand.",
    body_style
))

story.append(Paragraph("API Services and Resources Called", section_style))
story.append(Paragraph("• <b>GoogleAdsService</b> — Primary search query interface used to pull all reporting data via GAQL (Google Ads Query Language).", bullet_style))
story.append(Paragraph("• <b>Customer resource</b> — Retrieve account-level metadata and accessible accounts under the MCC.", bullet_style))
story.append(Paragraph("• <b>Campaign resource</b> — Pull campaign status, budget, bidding strategy, and performance metrics.", bullet_style))
story.append(Paragraph("• <b>AdGroup resource</b> — Retrieve ad group performance and status.", bullet_style))
story.append(Paragraph("• <b>Keyword resource (ad_group_criterion)</b> — Pull keyword-level performance including Quality Score, search impression share, and bid data.", bullet_style))
story.append(Paragraph("• <b>SearchTermView resource</b> — Retrieve search term reports to identify irrelevant queries for negative keyword management.", bullet_style))
story.append(Paragraph("• <b>CampaignBudget resource</b> — Monitor budget utilization and pacing.", bullet_style))

story.append(Paragraph("Data Flow", section_style))
story.append(Paragraph(
    "1. Script authenticates using OAuth 2.0 refresh token stored in a local credentials file.<br/>"
    "2. Script queries the Google Ads API via GoogleAdsService using GAQL for the target account(s).<br/>"
    "3. API response data is parsed and written to an Excel workbook using the openpyxl library.<br/>"
    "4. The resulting .xlsx file is saved to the operator's local machine for review and client delivery.<br/>"
    "5. No data is transmitted to any third-party service or stored in any cloud database.",
    body_style
))

story.append(Paragraph("Access Controls and Security", section_style))
story.append(Paragraph(
    "• OAuth 2.0 credentials and the developer token are stored in a local configuration file "
    "on the operator's personal computer, protected by full-disk encryption (macOS FileVault).<br/>"
    "• Access is restricted to a single authorized user (David Shiba).<br/>"
    "• No API credentials are shared, committed to version control, or transmitted externally.<br/>"
    "• Client account access is governed by Google Ads manager account permissions; only "
    "accounts explicitly linked to the MCC are accessible.",
    body_style
))

doc.build(story)
print(f"PDF written to: {output}")
